[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for all other files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data: https:; connect-src 'self'"

# Development settings
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# Production environment variables
[context.production]
  NODE_ENV = "production"
  VITE_API_URL = "/api"  # Update with your actual API URL

# Deploy preview settings
[context.deploy-preview]
  NODE_ENV = "staging"
  VITE_API_URL = "/api"  # Update with your staging API URL
